[package]
name = "mines"
version = "2.0.0"
authors = ["zo-el <joel.ulahanna@holo.host>"]
edition = "2018"

[dependencies]
serde = "=1.0.104"
thiserror = "1.0.22"
hdk3 = "0"
hc_utils = "0"
holo_hash = "0"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
